version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5050:5050"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=${NODE_ENV}
    env_file:
      - .env
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
